---

- name: Add KUBECONFIG to root .bashrc
  shell: |
    grep "KUBECONFIG={{ secret.install_dir }}/auth/kubeconfig" /root/.bashrc || echo export KUBECONFIG={{ secret.install_dir }}/auth/kubeconfig >> /root/.bashrc
  become: true
- pause: seconds=10

- name: reset ssh connection to allow user changes to affect 'current login user'
  meta: reset_connection
  