---

- name: Approving all pending CSR
  shell: |
    oc get csr | awk '{print $1'} | grep -v NAME | xargs oc adm certificate approve
  register: csr_approved_1
  ignore_errors: yes
#- name: viewing first csr approved
#  debug:
#    msg: "{{csr_approved_1.stdout_lines}}"
- pause: seconds=60

- name: Second round approving all pending CSR
  shell: |
    oc get csr | awk '{print $1'} | grep -v NAME | xargs oc adm certificate approve
  register: csr_approved_2
  ignore_errors: yes
- name: viewing second csr approved
  debug:
    msg: "{{csr_approved_2.stdout_lines}}"
- pause: seconds=60
