---

- name: Patching image-registry
  shell: |
    oc patch configs.imageregistry.operator.openshift.io cluster --type merge --patch '{"spec":{"storage":{"emptyDir":{}}}}'
- pause: seconds=120

- name: Third round approving all pending CSR
  shell: |
    oc get csr | awk '{print $1'} | grep -v NAME | xargs oc adm certificate approve
  register: csr_approved_3
  ignore_errors: yes
#- name: viewing third csr approved
#  debug:
#    msg: "{{csr_approved_3.stdout_lines}}"
- pause: seconds=60

- name: First check patch Implementation
  shell: oc get clusteroperators | awk '{print $3'}
  register: result
  until: result.stdout.find ("False") == -1
  retries: 20
  delay: 30
  ignore_errors: yes

- name: Fourth round approving all pending CSR
  shell: |
    oc get csr | awk '{print $1'} | grep -v NAME | xargs oc adm certificate approve
  register: csr_approved_4
  ignore_errors: yes
#- name: viewing fourth csr approved
#  debug:
#    msg: "{{csr_approved_4.stdout_lines}}"
- pause: seconds=60

- name: Fifth round approving all pending CSR
  shell: |
    oc get csr | awk '{print $1'} | grep -v NAME | xargs oc adm certificate approve
  register: csr_approved_4
  ignore_errors: yes
- name: viewing fifth csr approved
  debug:
    msg: "{{csr_approved_4.stdout_lines}}"
- pause: seconds=60

- name: Second check patch Implementation
  shell: oc get clusteroperators | awk '{print $3'}
  register: result
  until: result.stdout.find ("False") == -1
  retries: 20
  delay: 30