---

# vSphere info
vcenter: "vcenter"
username: "username"
password: "password"
datacenter: "datacenter"
cluster: "cluster"
datastore: "datastore"
network: "network"

# OVA info
ova_url: https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/latest/latest/rhcos-4.5.6-x86_64-vmware.x86_64.ova

# OpenShift info
ocp_cluster_name: "ocp cluster name"
ocp_domain_name: "ocp domain name.int"
ocp_pull_secret: "pull secret"

# Ignition files data
http_host: "IP Address"

# Bastion info
bastion_ip: "IP Address"

# Installer info
base_dir: /var/tmp
install_dir: /var/tmp/ocp-install
installer_url: https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-install-linux.tar.gz
client_url: https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-client-linux.tar.gz
client_name: oc_latest.tar.gz
installer_name: installer_latest.tar.gz
